// <auto-generated />
using System;
using FormApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241212113801_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormApp.Models.CMRAFormModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressIDPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessZIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatePMBClosed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePMBOpened")
                        .HasColumnType("datetime2");

                    b.Property<string>("Form1583Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PMBNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoIDPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddressDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CMRAFormModels");
                });
#pragma warning restore 612, 618
        }
    }
}
